name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Server Restart Scripts
        # uses: appleboy/ssh-action@v1.0.3
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: pwd
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
