name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare and Run Scripts
        run: |
          source ../../../../venv/bin/activate
          bash server-restart.sh
