name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare and Run Scripts
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} username@${{secrets.DROPLET_IP}} "sudo systemctl restart fossee.service"
